### ISSUE TITLE
Incorrect no drop item text

### ISSUE THREAD

**Issue by nickgal** [quarmdb/quarmdb#11]
I believe the check should be changed to `nodrop === 0`  https://github.com/quarmdb/quarmdb/blob/4c26bff6d706cca0bce8cbd25e1d9c538a426835/src/lib/components/ItemCard.svelte#L36

See also https://github.com/EQMacEmu/allaclone/blob/ec09ee3dc7329b362b8ea060353b7d0b72898e67/includes/functions.php#L853

Examples of incorrect items:
- Shows as drop-able https://www.quarmdb.com/items/2300/journeyman's-boots
- Shows as no drop https://www.quarmdb.com/items/4164/rubicite-breastplate

**Comment by joshuawjulian** [comment]
Thank you for this, updated.
