### ISSUE TITLE
EXP tables are off by a factor of 10

### ISSUE THREAD

**Issue by jarneson** [quarmdb/quarmdb#14]
This URL: https://www.quarmdb.com/info/exp shows 100 exp needed for level 2, when it should be 1000.

![image](https://github.com/quarmdb/quarmdb/assets/3580111/b97018e3-5ae6-4a3c-86a6-05204a8ad0a1)

**Comment by joshuawjulian** [comment]
https://github.com/SecretsOTheP/EQMacEmu/blob/09da8370ff01ea671fbc772511579b8d4876741e/zone/exp.cpp#L709

This is it. Thank you for pointing it out.

**Comment by joshuawjulian** [comment]
Updated with change
